### ISSUE TITLE
add option to define threads hardcoded

### ISSUE THREAD

**Issue by norg** [DCSO/slinkwatch#1]
In the case of symmetric queues it's recommended to use the same amount of threads, this might work with threadsweight but it might be better to force a specific amount of threads to ensure it's equal to the queue number

**Comment by satta** [comment]
Do you mean a fixed number of threads? That could just be changed in the template, I guess.
Can you give an example?

**Comment by norg** [comment]
```
# Interfaces available for Suricata
---
ifaces:
  ens5f0:
    threadweight: 8
    clusterid: 99
  ens5f1:
    threadweight: 8
    clusterid: 98
```
with
```
%YAML 1.1
---
af-packet:{{ range $iface, $vals := . }}
  - interface: {{ $iface }}
    threads: {{ $vals.Threads }}
    cluster-id: {{ $vals.ClusterID }}
    cluster-type: cluster_qm
    defrag: yes
    rollover: no
    use-mmap: yes
    tpacket-v3: yes
    use-emergency-flush: yes
{{ else }}
  - interface: ens5f0
    threads: auto
    use-mmap: yes
    rollover: yes
    tpacket-v3: yes
{{ end }}
```
results in
```
%YAML 1.1
---
af-packet:
  - interface: ens5f0
    threads: 16
    cluster-id: 99
    cluster-type: cluster_qm
    defrag: yes
    rollover: no
    use-mmap: yes
    tpacket-v3: yes
    use-emergency-flush: yes

  - interface: ens5f1
    threads: 16
    cluster-id: 98
    cluster-type: cluster_qm
    defrag: yes
    rollover: no
    use-mmap: yes
    tpacket-v3: yes
    use-emergency-flush: yes
```
What I would like to set the threads fixed to the value 8 instead of the weight being based.

**Comment by satta** [comment]
```yaml
%YAML 1.1
---
af-packet:{{ range $iface, $vals := . }}
  - interface: {{ $iface }}
    threads: 8
    cluster-id: {{ $vals.ClusterID }}
    cluster-type: cluster_qm
    defrag: yes
    rollover: no
    use-mmap: yes
    tpacket-v3: yes
    use-emergency-flush: yes
{{ else }}
  - interface: ens5f0
    threads: auto
    use-mmap: yes
    rollover: yes
    tpacket-v3: yes
{{ end }}
```

should do what you want. But then you won't get scaling to the number of CPUs when an interface goes away
