### ISSUE TITLE
add additional options to be configured 

### ISSUE THREAD

**Issue by norg** [DCSO/slinkwatch#2]
It would be great to configure the other settings as well, especially **cluster-type** although a sane default is still okay.

**Comment by satta** [comment]
Couldn't this just be configured in the template used in the slinkwatch installation?

**Comment by norg** [comment]
It could but if you want to have different settings on different interfaces this is something I would manage within the config, for example:
```
# Interfaces available for Suricata
---
ifaces:
  ens5f0:
    threadweight: 8
    clusterid: 99
    cluster-type: cluster_qm
  ens5f1:
    threadweight: 8
    clusterid: 98
    cluster-type: cluster_flow
```
